name: 📦 CI/CD
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: 🧪 test website
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: 🔨 Set npm
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache-dependency-path: package-lock.json

      - name: ⚒️ Setup project
        run: npm ci

      - name: 🛠️ Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: 🎭 Playwright
        run: npx playwright install
        env:
          NODE_ENV: production

      - name: 📋 Test
        run: npm run test
        env:
          NODE_ENV: production
